name: simple python pipeline

on:
  push:
    branches:
      - master

jobs: 
  simple_python_hi: 
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: simple python code hi
        run: python -c 'print("hi")'
          
  hello_job:
    needs: simple_python_hi
    runs-on: self-hosted

    steps:
      - name: python hello
        run: python -c 'print("hi")'
